In [1]:
import numpy as np

In [4]:
boy = [0.4, 0.3, 0.5, 0.8]
boy_w = [1, 0, 1, 0]
girl = [0.3, 0.4, 0.2, 0.1]
gril_w = [0, 1, 0, 0]
other = [0.3, 0.3, 0.3, 0.1]
other_w = [0, 0, 0, 1]

In [6]:
photo_rate = np.array([boy, girl, other], dtype=np.float32)
photo_weight = np.array([boy_w, gril_w, other_w], dtype=np.float32)

In [7]:
print(photo_rate)
print(photo_weight)

[[0.4 0.3 0.5 0.8]
 [0.3 0.4 0.2 0.1]
 [0.3 0.3 0.3 0.1]]
[[1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [29]:
-np.log2(photo_rate)

array([[1.321928  , 1.7369655 , 1.        , 0.32192808],
       [1.7369655 , 1.321928  , 2.321928  , 3.321928  ],
       [1.7369655 , 1.7369655 , 1.7369655 , 3.321928  ]], dtype=float32)

In [33]:
(-np.log2(photo_rate)*photo_weight).sum(axis=1).sum(axis=0)

6.965784

In [28]:
np.log2(0.4) + np.log2(0.5)

-2.321928094887362