In [2]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
tensor = torch.tensor([[1, 2]])
print(tensor)

tensor2 = torch.IntTensor([[1, 2]])
print(tensor2)

tensor3 = torch.LongTensor([[1, 2]])
print(tensor3)

tensor4 = torch.FloatTensor([[1, 2]])
print(tensor4)

tensor([[1, 2]])
tensor([[1, 2]], dtype=torch.int32)
tensor([[1, 2]])
tensor([[1., 2.]])


In [4]:
# 張量運算
A = torch.tensor([[1,2,3],
              [4,5,6]])
B = torch.tensor([[9,8,7],
              [7,6,5]
             ])

print(A + B)  # 加法
print(A - B)  # 減法
print(A * B)  # 乘法
print(A / B)  # 除法


tensor([[10, 10, 10],
        [11, 11, 11]])
tensor([[-8, -6, -4],
        [-3, -1,  1]])
tensor([[ 9, 16, 21],
        [28, 30, 30]])
tensor([[0.1111, 0.2500, 0.4286],
        [0.5714, 0.8333, 1.2000]])
tensor([[ 38,  32],
        [101,  86]])


In [5]:
# 內積
A = torch.tensor([[1,2,3],
              [4,5,6]])
B = torch.tensor([[9,8],
              [7,6],
              [5,4],
             ])
print(A @ B)

tensor([[ 38,  32],
        [101,  86]])


In [6]:
# PyTorch -> Numpy
(A @ B).numpy()

array([[ 38,  32],
       [101,  86]])

In [7]:
type((A @ B).numpy())

numpy.ndarray

In [8]:
import numpy as np

array = np.array([[1, 2]])
# Numpy -> PyTorch
tensor = torch.from_numpy(array)
tensor

tensor([[1, 2]])

In [9]:
# TensorFlow reduce_sum 的等式 
A = torch.FloatTensor([[1,2,3],
              [4,5,6]])
A.sum(axis=1)

tensor([ 6., 15.])

In [10]:
A = torch.tensor([[1,2,3],
              [4,5,6]])
print('矩陣A:\n', A.numpy(), '\n\n轉置')

# 轉置矩陣
print(A.T)
print(torch.transpose(A, 0, 1)) # 維度0/1被轉置

矩陣A:
 [[1 2 3]
 [4 5 6]] 

轉置
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [11]:
# A @ A反矩陣 = 單位矩陣(I)
A = torch.FloatTensor([[9,8],
              [7,6],
             ])

print(torch.inverse(A))

tensor([[-3.0000,  4.0000],
        [ 3.5000, -4.5000]])


In [12]:
# A @ A反矩陣 = 單位矩陣(I)
A = torch.FloatTensor([[9,8],
              [7,6],
             ])

print(torch.inverse(torch.inverse(A)))

tensor([[9.0000, 8.0000],
        [7.0000, 6.0000]])


In [3]:
# CPU -> GPU
tensor = torch.device("mps")
print(tensor)
print(torch.backends.mps.is_built())
print(torch.backends.mps.is_available())

mps
True
True


In [15]:
device = torch.device("mps")
print(device)

mps
